version: "3.9"

services:
  php:
    build: ./backend
    container_name: yi_php
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    networks:
      - yi-network

  nginx:
    image: nginx:stable
    container_name: yi_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html:ro
      - ./docker/nginx/backend.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - yi-network

  frontend:
    build: ./frontend
    container_name: yi_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - yi-network

  db:
    image: mysql:8.0
    container_name: yi_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: yiapi
      MYSQL_USER: yiiuser
      MYSQL_PASSWORD: yiipass
    volumes:
      - ./docker/db:/var/lib/mysql
    networks:
      - yi-network

networks:
  yi-network:
