services:
  backend:
    build: ./backend
    container_name: yii-backend
    volumes:
      - ./backend:/var/www/html
    networks:
      - app
    depends_on:
      - db
    # Faz o container reconhecer o host como host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:latest
    container_name: yii-nginx
    volumes:
      - ./backend:/var/www/html
      - ./nginx:/etc/nginx/conf.d
    ports:
      - "8080:80"
    networks:
      - app
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: yii-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yii_db
      MYSQL_USER: yiiuser
      MYSQL_PASSWORD: yiipass
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app
    ports:
    - "3306:3306"


networks:
  app:

volumes:
  db_data:
